import { NextRequest, NextResponse } from "next/server";

import { requireAdmin } from "@/lib/admin/require-admin";
import { supabaseAdmin } from "@/lib/supabase/server";

type RangeKey = "today" | "7d" | "30d" | "all";
type AnalyticsRow = { event_name:string; game_name:string|null; user_id:string|null; session_id:string|null; created_at:string; metadata:Record<string,unknown>|null };
type SoloSessionRow = { id:string; source_session_id:string|null; user_id:string|null; status:string; started_at:string; finished_at:string|null; duration_ms:number|null };
type ProfileRow = { id:string; created_at:string };

const PAGE_SIZE=1000;
const ABANDON_AFTER_MS=30*60*1000;
const SOLO_GAME_NAMES=new Set(["wordle","guess_the_player","super_lig_guess_the_player","player_quiz","transfer_quiz","tic_tac_toe","club_nation","club_clash","career_path","shooter"]);
function getStartDate(range:RangeKey){const now=new Date();if(range==="today"){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now);const y=parts.find(p=>p.type==="year")?.value,m=parts.find(p=>p.type==="month")?.value,d=parts.find(p=>p.type==="day")?.value;if(y&&m&&d)return new Date(`${y}-${m}-${d}T00:00:00+03:00`).toISOString()}if(range==="7d"||range==="30d"){const s=new Date(now);s.setDate(s.getDate()-(range==="7d"?7:30));return s.toISOString()}return null}
function average(v:number[]){return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0}
function dayKey(v:string){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(v))}
function visitorIdOf(m:Record<string,unknown>|null){const v=m?.visitor_id;return typeof v==="string"&&v.length>=8?v:null}
function platformOf(m:Record<string,unknown>|null){const v=m?.platform;return v==="android"?"android":v==="web"?"web":"unknown"}
function durationMsOf(m:Record<string,unknown>|null){const v=m?.duration_ms;return typeof v==="number"&&Number.isFinite(v)&&v>=0?v:null}
async function fetchAll(table:string,select:string,startDate?:string|null,dateColumn="created_at"){const rows:unknown[]=[];for(let from=0;;from+=PAGE_SIZE){let q=supabaseAdmin.from(table).select(select).order(dateColumn,{ascending:true}).range(from,from+PAGE_SIZE-1);if(startDate)q=q.gte(dateColumn,startDate);const {data,error}=await q;if(error)throw error;const b=(data??[]) as unknown[];rows.push(...b);if(b.length<PAGE_SIZE)break}return rows}

export async function GET(request:NextRequest){const admin=await requireAdmin();if(!admin.ok)return NextResponse.json({ok:false,error:admin.error},{status:admin.status});try{const raw=request.nextUrl.searchParams.get("range");const range:RangeKey=raw==="today"||raw==="30d"||raw==="all"?raw:"7d";const startDate=getStartDate(range),sevenDaysAgo=new Date(Date.now()-7*86400000).toISOString();const {error:reconcileError}=await supabaseAdmin.rpc("reconcile_solo_session_lifecycle");if(reconcileError)console.error("Solo lifecycle reconcile failed:",reconcileError);
const [analyticsRows,soloRows]=await Promise.all([fetchAll("analytics_events","event_name,game_name,user_id,session_id,created_at,metadata",startDate) as Promise<AnalyticsRow[]>,fetchAll("game_sessions","id,source_session_id,user_id,status,started_at,finished_at,duration_ms",startDate,"started_at") as Promise<SoloSessionRow[]>]);
const nativeBySession=new Map<string,SoloSessionRow>();for(const r of soloRows){nativeBySession.set(r.id,r);if(r.source_session_id)nativeBySession.set(r.source_session_id,r)}
const starts=new Map<string,AnalyticsRow>(),completions=new Map<string,AnalyticsRow>(),actionCounts=new Map<string,number>(),replayKeys=new Set<string>(),replayByGame=new Map<string,number>(),sharedByGame=new Map<string,number>(),selectedUsers=new Set<string>(),selectedAnonymousVisitors=new Set<string>(),dailyUsers=new Map<string,Set<string>>();const platforms={web:0,android:0,unknown:0};
for(const row of analyticsRows){const game=row.game_name??"unknown";if(!SOLO_GAME_NAMES.has(game))continue;if(row.user_id){selectedUsers.add(row.user_id);const k=dayKey(row.created_at),s=dailyUsers.get(k)??new Set<string>();s.add(row.user_id);dailyUsers.set(k,s)}const visitor=visitorIdOf(row.metadata);if(!row.user_id&&visitor)selectedAnonymousVisitors.add(visitor);if(!row.session_id){if(row.event_name==="shared"||row.event_name==="game_shared")sharedByGame.set(game,(sharedByGame.get(game)??0)+1);continue}const key=`${game}:${row.session_id}`;if(row.event_name==="game_started"){if(!starts.has(key)){starts.set(key,row);platforms[platformOf(row.metadata)]+=1}}else if(row.event_name==="game_completed")completions.set(key,row);else if(row.event_name==="game_action")actionCounts.set(key,(actionCounts.get(key)??0)+1);else if(row.event_name==="play_again"){if(!replayKeys.has(key)){replayKeys.add(key);replayByGame.set(game,(replayByGame.get(game)??0)+1)}}else if(row.event_name==="shared"||row.event_name==="game_shared")sharedByGame.set(game,(sharedByGame.get(game)??0)+1)}
type Bucket={gameName:string;started:number;activePlayers:number;completed:number;noActionExit:number;realAbandoned:number;technicalSuspect:number;inProgress:number;durations:number[];users:Set<string>;anonymousVisitors:Set<string>};const gameMap=new Map<string,Bucket>();const ensure=(g:string)=>{if(!gameMap.has(g))gameMap.set(g,{gameName:g,started:0,activePlayers:0,completed:0,noActionExit:0,realAbandoned:0,technicalSuspect:0,inProgress:0,durations:[],users:new Set(),anonymousVisitors:new Set()});return gameMap.get(g)!};const now=Date.now();
for(const [key,start] of starts){const gameName=start.game_name!,sessionId=start.session_id!,g=ensure(gameName);g.started++;const visitor=visitorIdOf(start.metadata);if(start.user_id)g.users.add(start.user_id);else if(visitor)g.anonymousVisitors.add(visitor);const actions=actionCounts.get(key)??0;if(actions>0)g.activePlayers++;const completion=completions.get(key),native=nativeBySession.get(sessionId),nativeCompleted=native?.status==="finished"||native?.status==="rejected",completed=Boolean(completion)||nativeCompleted;if(completed){g.completed++;const explicit=completion?durationMsOf(completion.metadata):null,nativeDuration=Number(native?.duration_ms??0),measured=completion?new Date(completion.created_at).getTime()-new Date(start.created_at).getTime():native?.finished_at?new Date(native.finished_at).getTime()-new Date(start.created_at).getTime():0,durationMs=explicit??(nativeDuration>0?nativeDuration:measured),seconds=Math.round(durationMs/1000);if(seconds>=1&&seconds<=3600)g.durations.push(seconds);continue}const oldEnough=now-new Date(start.created_at).getTime()>=ABANDON_AFTER_MS;if(!oldEnough&&native?.status!=="abandoned"){g.inProgress++;continue}if(actions===0){g.noActionExit++;continue}const metadataTechnical=analyticsRows.some(r=>r.session_id===sessionId&&r.game_name===gameName&&(r.event_name==="game_error"||r.event_name==="technical_error"));if(metadataTechnical)g.technicalSuspect++;else g.realAbandoned++}
for(const name of new Set([...replayByGame.keys(),...sharedByGame.keys()]))ensure(name);const games=Array.from(gameMap.values()).map(g=>({gameName:g.gameName,started:g.started,activePlayers:g.activePlayers,completed:g.completed,noActionExit:g.noActionExit,realAbandoned:g.realAbandoned,technicalSuspect:g.technicalSuspect,abandoned:g.noActionExit+g.realAbandoned+g.technicalSuspect,inProgress:g.inProgress,playAgain:replayByGame.get(g.gameName)??0,shared:sharedByGame.get(g.gameName)??0,uniqueUsers:g.users.size,loggedInUsers:g.users.size,anonymousVisitors:g.anonymousVisitors.size,completionRate:g.started?Number((g.completed/g.started*100).toFixed(1)):0,averageDurationSeconds:average(g.durations)})).filter(g=>g.started||g.playAgain||g.shared).sort((a,b)=>b.started-a.started);
const summary={totalStarted:games.reduce((s,g)=>s+g.started,0),totalActivePlayers:games.reduce((s,g)=>s+g.activePlayers,0),totalCompleted:games.reduce((s,g)=>s+g.completed,0),totalNoActionExit:games.reduce((s,g)=>s+g.noActionExit,0),totalRealAbandoned:games.reduce((s,g)=>s+g.realAbandoned,0),totalTechnicalSuspect:games.reduce((s,g)=>s+g.technicalSuspect,0),totalAbandoned:games.reduce((s,g)=>s+g.abandoned,0),totalInProgress:games.reduce((s,g)=>s+g.inProgress,0),totalPlayAgain:games.reduce((s,g)=>s+g.playAgain,0),totalShared:games.reduce((s,g)=>s+g.shared,0),averageDurationSeconds:average(games.flatMap(g=>gameMap.get(g.gameName)?.durations??[]))};
const wauRows=(await fetchAll("analytics_events","user_id,created_at",sevenDaysAgo)) as Array<{user_id:string|null;created_at:string}>;const wau=new Set(wauRows.map(r=>r.user_id).filter(Boolean)).size,today=dayKey(new Date().toISOString()),dau=dailyUsers.get(today)?.size??new Set(wauRows.filter(r=>dayKey(r.created_at)===today).map(r=>r.user_id).filter(Boolean)).size,profileRows=(await fetchAll("profiles","id,created_at",startDate)) as ProfileRow[];return NextResponse.json({ok:true,source:"event_based_action_funnel",range,summary,audience:{dau,wau,uniquePlayers:selectedUsers.size,anonymousPlayers:selectedAnonymousVisitors.size,newUsers:profileRows.length,platforms},games})}catch(error){console.error("Admin analytics error:",error);return NextResponse.json({ok:false,error:"Analytics verileri hazırlanamadı."},{status:500})}}
