"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type RangeKey = "today" | "7d" | "30d" | "all";
type GameAnalyticsRow = { gameName: string; started: number; completed: number; abandoned: number; playAgain: number; shared: number; uniqueUsers: number; completionRate: number; averageDurationSeconds: number };
type DuelSummary = { created: number; accepted: number; started: number; completed: number; rejected: number; cancelled: number; uniquePlayers: number };
type DuelGameRow = { gameCode: string; created: number; accepted: number; started: number; completed: number; rejected: number; cancelled: number };
type SurvivorAnalyticsRow = { id: string; slug: string; title: string; isActive: boolean; completions: number };
type AnalyticsSummary = { totalStarted: number; totalCompleted: number; totalAbandoned: number; totalPlayAgain: number; totalShared: number; averageDurationSeconds: number };
type Audience = { dau: number; wau: number; uniquePlayers: number; newUsers: number; platforms: { web: number; android: number; unknown: number } };
type AnalyticsResponse = { ok?: boolean; error?: string; summary?: AnalyticsSummary; audience?: Audience; games?: GameAnalyticsRow[]; duelSummary?: DuelSummary; duelGames?: DuelGameRow[]; survivors?: SurvivorAnalyticsRow[] };
const RANGE_OPTIONS: Array<{ key: RangeKey; label: string }> = [{ key: "today", label: "Bugün" },{ key: "7d", label: "Son 7 Gün" },{ key: "30d", label: "Son 30 Gün" },{ key: "all", label: "Tümü" }];
const GAME_LABELS: Record<string,string> = { wordle:"Wordle",guess_the_player:"Guess the Player",super_lig_guess_the_player:"Süper Lig Guess the Player",player_quiz:"Player Quiz",transfer_quiz:"Transfer Quiz",tic_tac_toe:"Futbol Tic Tac Toe",club_nation:"1 Takım 1 Millet",club_clash:"2 Takım 1 Oyuncu",career_path:"Career Path" };
const EMPTY_SUMMARY: AnalyticsSummary = { totalStarted:0,totalCompleted:0,totalAbandoned:0,totalPlayAgain:0,totalShared:0,averageDurationSeconds:0 };
const EMPTY_DUEL_SUMMARY: DuelSummary = { created:0,accepted:0,started:0,completed:0,rejected:0,cancelled:0,uniquePlayers:0 };
const EMPTY_AUDIENCE: Audience = { dau:0,wau:0,uniquePlayers:0,newUsers:0,platforms:{web:0,android:0,unknown:0} };
function getGameLabel(n:string){return GAME_LABELS[n]??n} function formatNumber(v:number){return new Intl.NumberFormat("tr-TR").format(v)} function formatPercentage(v:number){return `%${new Intl.NumberFormat("tr-TR",{minimumFractionDigits:1,maximumFractionDigits:1}).format(v)}`} function formatDuration(s:number){if(!s)return "-";if(s<60)return `${s} sn`;const m=Math.floor(s/60),r=s%60;return r?`${m} dk ${r} sn`:`${m} dk`}
export default function AdminAnalyticsPage(){
 const[range,setRange]=useState<RangeKey>("7d"),[loading,setLoading]=useState(true),[error,setError]=useState(""); const[summary,setSummary]=useState(EMPTY_SUMMARY),[audience,setAudience]=useState(EMPTY_AUDIENCE),[games,setGames]=useState<GameAnalyticsRow[]>([]),[duelSummary,setDuelSummary]=useState(EMPTY_DUEL_SUMMARY),[duelGames,setDuelGames]=useState<DuelGameRow[]>([]),[survivors,setSurvivors]=useState<SurvivorAnalyticsRow[]>([]);
 useEffect(()=>{void loadAnalytics()},[range]); async function loadAnalytics(){try{setLoading(true);setError("");const response=await fetch(`/api/admin/analytics?range=${encodeURIComponent(range)}`,{cache:"no-store"});const result=await response.json() as AnalyticsResponse;if(!response.ok||!result.ok)throw new Error(result.error??"Analytics verileri yüklenemedi.");setSummary(result.summary??EMPTY_SUMMARY);setAudience(result.audience??EMPTY_AUDIENCE);setGames(result.games??[]);setDuelSummary(result.duelSummary??EMPTY_DUEL_SUMMARY);setDuelGames(result.duelGames??[]);setSurvivors(result.survivors??[])}catch(e){setError(e instanceof Error?e.message:"Analytics verileri yüklenemedi.")}finally{setLoading(false)}}
 const overall=summary.totalStarted?(summary.totalCompleted/summary.totalStarted)*100:0,mostPlayed=useMemo(()=>[...games].sort((a,b)=>b.started-a.started)[0]??null,[games]),mostAbandoned=useMemo(()=>[...games].sort((a,b)=>b.abandoned-a.abandoned)[0]??null,[games]); const accept=duelSummary.created?(duelSummary.accepted/duelSummary.created)*100:0,start=duelSummary.accepted?(duelSummary.started/duelSummary.accepted)*100:0,complete=duelSummary.started?(duelSummary.completed/duelSummary.started)*100:0; const known=audience.platforms.web+audience.platforms.android,androidRate=known?(audience.platforms.android/known)*100:0;
 return <main className="min-h-screen bg-[#07111f] px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-7xl">
 <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-green-400">FootBattle Admin</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Oyun Raporları</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Kullanıcı, platform, oyun, düello ve Survivor performansını tek ekrandan takip et.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/analytics/ranked" className="rounded-xl border border-green-400/30 bg-green-400/10 px-4 py-2.5 text-xs font-black text-green-300">🏆 Ranked</Link>{RANGE_OPTIONS.map(o=><button key={o.key} onClick={()=>setRange(o.key)} className={`rounded-xl px-4 py-2.5 text-xs font-black ${range===o.key?"bg-green-500 text-[#07111f]":"border border-white/10 bg-white/[0.03] text-slate-400"}`}>{o.label}</button>)}</div></div>{error&&<div className="mt-6 rounded-2xl border border-red-500/20 bg-red-500/10 px-5 py-4 text-sm font-bold text-red-300">{error}</div>}
 <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><SummaryCard label="DAU" value={formatNumber(audience.dau)} icon="👤" loading={loading}/><SummaryCard label="WAU" value={formatNumber(audience.wau)} icon="👥" loading={loading}/><SummaryCard label="Tekil Oyuncu" value={formatNumber(audience.uniquePlayers)} icon="🎯" loading={loading}/><SummaryCard label="Yeni Kullanıcı" value={formatNumber(audience.newUsers)} icon="✨" loading={loading}/><SummaryCard label="Web Başlatma" value={formatNumber(audience.platforms.web)} icon="🌐" loading={loading}/><SummaryCard label="Android Başlatma" value={formatNumber(audience.platforms.android)} icon="📱" loading={loading}/></section>
 <section className="mt-4 grid gap-4 lg:grid-cols-3"><InsightCard label="Android Payı" value={formatPercentage(androidRate)} detail={`${formatNumber(audience.platforms.unknown)} eski/etiketsiz başlangıç platform oranına dahil edilmedi.`} tone="green"/><InsightCard label="Genel Tamamlama" value={formatPercentage(overall)} detail="Tamamlanan / başlatılan oyun." tone="green"/><InsightCard label="En Çok Oynanan" value={mostPlayed?getGameLabel(mostPlayed.gameName):"-"} detail={mostPlayed?`${formatNumber(mostPlayed.started)} başlangıç · ${formatNumber(mostPlayed.uniqueUsers)} tekil kullanıcı`:"Henüz veri yok."} tone="yellow"/></section>
 <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><SummaryCard label="Başlatma" value={formatNumber(summary.totalStarted)} icon="🎮" loading={loading}/><SummaryCard label="Tamamlama" value={formatNumber(summary.totalCompleted)} icon="✅" loading={loading}/><SummaryCard label="Tahmini Terk" value={formatNumber(summary.totalAbandoned)} icon="🚪" loading={loading}/><SummaryCard label="Ort. Süre" value={formatDuration(summary.averageDurationSeconds)} icon="⏱️" loading={loading}/><SummaryCard label="Tekrar Oyna" value={formatNumber(summary.totalPlayAgain)} icon="🔁" loading={loading}/><SummaryCard label="Paylaşım" value={formatNumber(summary.totalShared)} icon="📤" loading={loading}/></section>
 <section className="mt-4 grid gap-4 lg:grid-cols-2"><InsightCard label="En Çok Terk Edilen" value={mostAbandoned?getGameLabel(mostAbandoned.gameName):"-"} detail={mostAbandoned?`${formatNumber(mostAbandoned.abandoned)} tahmini terk.`:"Henüz veri yok."} tone="red"/><InsightCard label="WAU / DAU" value={audience.dau?`${(audience.wau/audience.dau).toFixed(1)}x`:"-"} detail="Son 7 gün aktif kullanıcı / bugün aktif kullanıcı." tone="yellow"/></section>
 <section className="mt-8 overflow-hidden rounded-2xl border border-green-400/15 bg-green-400/[0.025]"><div className="border-b border-white/10 px-5 py-4"><p className="font-black">⚔️ Düello Funnel</p></div><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><MiniCard label="Davet" value={formatNumber(duelSummary.created)}/><MiniCard label="Kabul" value={formatNumber(duelSummary.accepted)}/><MiniCard label="Başladı" value={formatNumber(duelSummary.started)}/><MiniCard label="Tamamlandı" value={formatNumber(duelSummary.completed)}/><MiniCard label="Reddedildi" value={formatNumber(duelSummary.rejected)}/><MiniCard label="İptal" value={formatNumber(duelSummary.cancelled)}/><MiniCard label="Tekil Oyuncu" value={formatNumber(duelSummary.uniquePlayers)}/></div><div className="grid gap-3 border-t border-white/10 p-5 md:grid-cols-3"><InsightCard label="Davet → Kabul" value={formatPercentage(accept)} detail="Davet dönüşümü." tone="green"/><InsightCard label="Kabul → Başlama" value={formatPercentage(start)} detail="Kabulden oyuna geçiş." tone="yellow"/><InsightCard label="Başlama → Bitiş" value={formatPercentage(complete)} detail="Başlatılan düelloların bitiş oranı." tone="green"/></div><div className="overflow-x-auto border-t border-white/10"><table className="w-full min-w-[720px] text-left"><thead><tr className="text-xs text-slate-500"><th className="p-4">Oyun</th><th>Davet</th><th>Kabul</th><th>Başladı</th><th>Bitti</th><th>Red</th><th>İptal</th></tr></thead><tbody>{duelGames.map(g=><tr key={g.gameCode} className="border-t border-white/5"><td className="p-4 font-black">{getGameLabel(g.gameCode)}</td><td>{g.created}</td><td>{g.accepted}</td><td>{g.started}</td><td>{g.completed}</td><td>{g.rejected}</td><td>{g.cancelled}</td></tr>)}</tbody></table></div></section>
 <section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="font-black">Oyun Bazlı Performans</p><p className="mt-1 text-xs text-slate-500">Tekil kullanıcı dahil session funnel.</p></div><button onClick={()=>void loadAnalytics()} disabled={loading} className="rounded-xl border border-white/10 px-4 py-2 text-xs font-black">Yenile</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="text-xs text-slate-500"><th className="p-4">Oyun</th><th>Tekil</th><th>Başlatma</th><th>Tamamlama</th><th>Terk</th><th>Oran</th><th>Ort. Süre</th><th>Tekrar</th><th>Paylaşım</th></tr></thead><tbody>{games.map(g=><tr key={g.gameName} className="border-t border-white/5"><td className="p-4 font-black">{getGameLabel(g.gameName)}</td><td>{formatNumber(g.uniqueUsers)}</td><td>{formatNumber(g.started)}</td><td>{formatNumber(g.completed)}</td><td>{formatNumber(g.abandoned)}</td><td><CompletionBadge value={g.completionRate}/></td><td>{formatDuration(g.averageDurationSeconds)}</td><td>{formatNumber(g.playAgain)}</td><td>{formatNumber(g.shared)}</td></tr>)}</tbody></table></div></section>
 <section className="mt-8 overflow-hidden rounded-2xl border border-yellow-300/15 bg-yellow-300/[0.025]"><div className="border-b border-white/10 px-5 py-4"><p className="font-black">O Mu Bu Mu? / Survivor Tamamlamaları</p></div><div className="divide-y divide-white/5">{survivors.length===0?<div className="p-5 text-slate-500">Henüz Survivor sonucu yok.</div>:survivors.map((s,i)=><div key={s.id} className="flex justify-between px-5 py-4"><p className="font-black">#{i+1} {s.title}</p><p className="font-black text-yellow-200">{formatNumber(s.completions)}</p></div>)}</div></section>
 </div></main>}
function SummaryCard({label,value,icon,loading}:{label:string;value:string;icon:string;loading:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex justify-between"><p className="text-[10px] font-black uppercase text-slate-500">{label}</p><span>{icon}</span></div><p className="mt-3 text-2xl font-black">{loading?"...":value}</p></div>}
function MiniCard({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-black/10 p-4"><p className="text-[10px] font-black uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>}
function InsightCard({label,value,detail,tone}:{label:string;value:string;detail:string;tone:"green"|"yellow"|"red"}){const c=tone==="green"?"text-green-400":tone==="yellow"?"text-yellow-300":"text-red-300";return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${c}`}>{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>}
function CompletionBadge({value}:{value:number}){const c=value>=70?"text-green-300":value>=40?"text-yellow-300":"text-red-300";return <span className={`font-black ${c}`}>{formatPercentage(value)}</span>}
