"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import ActivePresenceCards from "@/components/admin/ActivePresenceCards";

type RangeKey = "today" | "7d" | "30d" | "all";
type GameAnalyticsRow = { gameName:string; started:number; completed:number; abandoned:number; inProgress:number; playAgain:number; shared:number; uniqueUsers:number; loggedInUsers:number; anonymousVisitors:number; completionRate:number; averageDurationSeconds:number };
type AnalyticsSummary = { totalStarted:number; totalCompleted:number; totalAbandoned:number; totalInProgress:number; totalPlayAgain:number; totalShared:number; averageDurationSeconds:number };
type Audience = { dau:number; wau:number; uniquePlayers:number; anonymousPlayers:number; newUsers:number; platforms:{web:number;android:number;unknown:number} };
type AnalyticsResponse = { ok?:boolean; error?:string; summary?:AnalyticsSummary; audience?:Audience; games?:GameAnalyticsRow[] };
const RANGE_OPTIONS:Array<{key:RangeKey;label:string}>=[{key:"today",label:"Bugün"},{key:"7d",label:"Son 7 Gün"},{key:"30d",label:"Son 30 Gün"},{key:"all",label:"Tümü"}];
const GAME_LABELS:Record<string,string>={wordle:"Wordle",guess_the_player:"Guess the Player",super_lig_guess_the_player:"Süper Lig Guess the Player",player_quiz:"Player Quiz",transfer_quiz:"Transfer Quiz",tic_tac_toe:"Futbol Tic Tac Toe",club_nation:"1 Takım 1 Millet",club_clash:"2 Takım 1 Oyuncu",career_path:"Career Path",shooter:"Şutör"};
const EMPTY_SUMMARY:AnalyticsSummary={totalStarted:0,totalCompleted:0,totalAbandoned:0,totalInProgress:0,totalPlayAgain:0,totalShared:0,averageDurationSeconds:0};
const EMPTY_AUDIENCE:Audience={dau:0,wau:0,uniquePlayers:0,anonymousPlayers:0,newUsers:0,platforms:{web:0,android:0,unknown:0}};
function gameLabel(v:string){return GAME_LABELS[v]??v} function n(v:number){return new Intl.NumberFormat("tr-TR").format(v)} function pct(v:number){return `%${new Intl.NumberFormat("tr-TR",{maximumFractionDigits:1}).format(v)}`} function duration(s:number){if(!s)return "-";if(s<60)return `${s} sn`;const m=Math.floor(s/60),r=s%60;return r?`${m} dk ${r} sn`:`${m} dk`} function gameUsers(g:GameAnalyticsRow){return g.loggedInUsers+g.anonymousVisitors} function replayRate(g:GameAnalyticsRow){return g.started?(g.playAgain/g.started)*100:0} function abandonRate(g:GameAnalyticsRow){return g.started?(g.abandoned/g.started)*100:0} function health(g:GameAnalyticsRow){if(g.started<5)return {label:"Veri az",cls:"text-slate-300 bg-slate-500/10 border-slate-400/20"};if(g.completionRate>=70&&abandonRate(g)<=25)return {label:"İyi",cls:"text-emerald-300 bg-emerald-500/10 border-emerald-400/20"};if(g.completionRate<40||abandonRate(g)>=50)return {label:"Sorunlu",cls:"text-red-300 bg-red-500/10 border-red-400/20"};return {label:"İncele",cls:"text-yellow-200 bg-yellow-500/10 border-yellow-300/20"}}
export default function AdminAnalyticsPage(){
 const [range,setRange]=useState<RangeKey>("today"),[loading,setLoading]=useState(true),[error,setError]=useState(""); const [summary,setSummary]=useState(EMPTY_SUMMARY),[audience,setAudience]=useState(EMPTY_AUDIENCE),[games,setGames]=useState<GameAnalyticsRow[]>([]),[details,setDetails]=useState(false); useEffect(()=>{void load()},[range]);
 async function load(){try{setLoading(true);setError("");const r=await fetch(`/api/admin/analytics?range=${encodeURIComponent(range)}`,{cache:"no-store"});const x=await r.json() as AnalyticsResponse;if(!r.ok||!x.ok)throw new Error(x.error??"Analytics verileri yüklenemedi.");setSummary(x.summary??EMPTY_SUMMARY);setAudience(x.audience??EMPTY_AUDIENCE);setGames(x.games??[])}catch(e){setError(e instanceof Error?e.message:"Analytics verileri yüklenemedi.")}finally{setLoading(false)}}
 const completion=summary.totalStarted?(summary.totalCompleted/summary.totalStarted)*100:0, abandoned=summary.totalStarted?(summary.totalAbandoned/summary.totalStarted)*100:0; const sorted=useMemo(()=>[...games].sort((a,b)=>b.started-a.started),[games]);
 return <main className="min-h-screen bg-[#07111f] px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.22em] text-green-400">FootBattle Admin</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Oyun Özeti</h1><p className="mt-2 text-sm text-slate-400">Tamamlanma eventi session durumundan üstündür. Terk, tamamlanmamış ve 30 dakikadan uzun süredir kapanmamış oturumdur.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/analytics/ranked" className="rounded-xl border border-green-400/30 bg-green-400/10 px-4 py-2.5 text-xs font-black text-green-300">🏆 Ranked</Link><Link href="/admin/analytics/survivor" className="rounded-xl border border-green-400/30 bg-green-400/10 px-4 py-2.5 text-xs font-black text-green-300">⚔️ Survivor</Link>{RANGE_OPTIONS.map(o=><button key={o.key} onClick={()=>setRange(o.key)} className={`rounded-xl px-4 py-2.5 text-xs font-black ${range===o.key?"bg-green-500 text-[#07111f]":"border border-white/10 bg-white/[.03] text-slate-400"}`}>{o.label}</button>)}</div></header>{error&&<div className="mt-6 rounded-2xl border border-red-500/20 bg-red-500/10 p-4 text-sm font-bold text-red-300">{error}</div>}<ActivePresenceCards/><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Card label="DAU" value={n(audience.dau)} sub="Bugünkü girişli tekil kullanıcı" loading={loading}/><Card label="Oyun Başlatma" value={n(summary.totalStarted)} sub="Seçili dönemde" loading={loading}/><Card label="Tamamlama" value={pct(completion)} sub={`${n(summary.totalCompleted)} tamamlanan`} loading={loading}/><Card label="Terk" value={pct(abandoned)} sub={`${n(summary.totalAbandoned)} gerçek terk`} loading={loading}/><Card label="Devam Eden" value={n(summary.totalInProgress)} sub="Henüz terk sayılmayan" loading={loading}/></section>
 <section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[.025]"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><h2 className="font-black">Oyun Performansı</h2><p className="mt-1 text-xs text-slate-500">Başlatma = gerçek session/event. Tamamlandı = session finished veya game_completed. Terk = completion yok + lifecycle süresi dolmuş.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-white/10 px-4 py-2 text-xs font-black">Yenile</button></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead><tr className="text-xs text-slate-500"><th className="p-4">Durum</th><th>Oyun</th><th>Oyuncu</th><th>Başlatma</th><th>Tamamlandı</th><th>Terk</th><th>Devam</th><th>Tamamlama</th><th>Ort. Süre</th><th>Tekrar</th></tr></thead><tbody>{sorted.map(g=>{const h=health(g);return <tr key={g.gameName} className="border-t border-white/5"><td className="p-4"><span className={`rounded-full border px-2.5 py-1 text-[10px] font-black uppercase ${h.cls}`}>{h.label}</span></td><td className="font-black">{gameLabel(g.gameName)}</td><td>{n(gameUsers(g))}</td><td>{n(g.started)}</td><td>{n(g.completed)}</td><td>{n(g.abandoned)}</td><td>{n(g.inProgress)}</td><td className="font-black">{pct(g.completionRate)}</td><td>{duration(g.averageDurationSeconds)}</td><td>{pct(replayRate(g))}</td></tr>})}</tbody></table></div></section>
 <div className="mt-6 flex justify-center"><button onClick={()=>setDetails(v=>!v)} className="rounded-xl border border-white/10 bg-white/[.035] px-5 py-3 text-xs font-black text-slate-300">{details?"Teknik Detayları Gizle":"Teknik Detayları Göster"}</button></div>{details&&<section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="WAU" value={n(audience.wau)} sub="Son 7 gün girişli tekil" loading={loading}/><Card label="Dönemsel Girişli" value={n(audience.uniquePlayers)} sub="Seçili tarih filtresi" loading={loading}/><Card label="Dönemsel Guest" value={n(audience.anonymousPlayers)} sub="Tanımlanabilir guest" loading={loading}/><Card label="Tekrar Oyna" value={n(summary.totalPlayAgain)} sub="Seçili dönemde" loading={loading}/></section>}</div></main>}
function Card({label,value,sub,loading}:{label:string;value:string;sub:string;loading:boolean}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><p className="text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-3 text-3xl font-black">{loading?"...":value}</p><p className="mt-2 text-xs text-slate-500">{sub}</p></div>}
