"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Faceoff={id:string;matchDate:string;title:string;category:string;titleTr:string;titleEn:string;categoryTr:string;categoryEn:string;leftName:string;rightName:string;isActive:boolean;votes:{total:number;left:number;right:number}};
type FormState={id:string;matchDate:string;titleTr:string;titleEn:string;categoryTr:string;categoryEn:string;leftName:string;rightName:string;isActive:boolean};
const EMPTY_FORM:FormState={id:"",matchDate:"",titleTr:"Günün Kapışması",titleEn:"Daily Faceoff",categoryTr:"Genel",categoryEn:"General",leftName:"",rightName:"",isActive:true};

export default function AdminFaceoffsPage(){
 const[items,setItems]=useState<Faceoff[]>([]);const[form,setForm]=useState<FormState>(EMPTY_FORM);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 const editing=Boolean(form.id);const totalVotes=useMemo(()=>items.reduce((s,i)=>s+i.votes.total,0),[items]);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/faceoffs",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error??"Kapışmalar yüklenemedi.");setItems(j.items??[])}catch(e){setMessage(e instanceof Error?e.message:"Kapışmalar yüklenemedi.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function edit(item:Faceoff){setForm({id:item.id,matchDate:item.matchDate,titleTr:item.titleTr,titleEn:item.titleEn,categoryTr:item.categoryTr,categoryEn:item.categoryEn,leftName:item.leftName,rightName:item.rightName,isActive:item.isActive});window.scrollTo({top:0,behavior:"smooth"})}
 async function save(){if(!form.matchDate||!form.leftName.trim()||!form.rightName.trim()){setMessage("Tarih ve iki oyuncu zorunlu.");return}setSaving(true);setMessage("");try{const r=await fetch("/api/admin/faceoffs",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error??"Kayıt yapılamadı.");setMessage(editing?"Kapışma güncellendi ✓":"Kapışma oluşturuldu ✓");setForm(EMPTY_FORM);await load()}catch(e){setMessage(e instanceof Error?e.message:"Kayıt yapılamadı.")}finally{setSaving(false)}}
 async function toggle(item:Faceoff){const r=await fetch("/api/admin/faceoffs",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,isActive:!item.isActive})});const j=await r.json();if(!r.ok||!j.ok)setMessage(j.error??"Durum güncellenemedi.");else await load()}
 async function remove(item:Faceoff){if(!window.confirm(`${item.leftName} - ${item.rightName} kapışması silinsin mi?`))return;const r=await fetch("/api/admin/faceoffs",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id})});const j=await r.json();if(!r.ok||!j.ok)setMessage(j.error??"Kapışma silinemedi.");else{if(form.id===item.id)setForm(EMPTY_FORM);await load()}}
 return <main className="min-h-screen bg-[#07111f] text-white"><div className="mx-auto max-w-7xl px-4 py-7 sm:px-6">
  <header className="flex flex-col gap-5 border-b border-white/10 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex gap-2"><Link href="/admin" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold text-slate-400">← Admin Panel</Link><Link href="/tr/daily-faceoff" className="rounded-xl border border-green-400/20 bg-green-400/10 px-4 py-2 text-sm font-bold text-green-300">🔥 Canlı Sayfa</Link></div><p className="mt-6 text-xs font-black uppercase tracking-[.22em] text-orange-300">Topluluk İçeriği</p><h1 className="mt-2 text-4xl font-black">Günün Kapışması Yönetimi</h1><p className="mt-3 text-sm text-slate-400">Başlık ve kategori TR/EN tutulur. Oyuncu isimlerini tek kez girmen yeterli.</p></div><div className="flex gap-3"><Stat value={String(items.length)} label="Kapışma"/><Stat value={String(totalVotes)} label="Toplam Oy"/></div></header>
  <section className="mt-7 rounded-3xl border border-white/10 bg-[#0d1828] p-5 sm:p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{editing?"Kapışmayı Güncelle":"Yeni Günün Kapışması"}</h2>{editing&&<button onClick={()=>setForm(EMPTY_FORM)} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold text-slate-400">Vazgeç</button>}</div>
   <div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Tarih"><input type="date" value={form.matchDate} onChange={(e)=>setForm({...form,matchDate:e.target.value})} className="input"/></Field><Field label="Kategori (TR)"><input value={form.categoryTr} onChange={(e)=>setForm({...form,categoryTr:e.target.value})} className="input"/></Field><Field label="Category (EN)"><input value={form.categoryEn} onChange={(e)=>setForm({...form,categoryEn:e.target.value})} className="input"/></Field><Field label="Başlık (TR)"><input value={form.titleTr} onChange={(e)=>setForm({...form,titleTr:e.target.value})} className="input"/></Field><Field label="Title (EN)"><input value={form.titleEn} onChange={(e)=>setForm({...form,titleEn:e.target.value})} className="input"/></Field><Field label="Sol Oyuncu"><input value={form.leftName} onChange={(e)=>setForm({...form,leftName:e.target.value})} placeholder="Lionel Messi" className="input"/></Field><Field label="Sağ Oyuncu"><input value={form.rightName} onChange={(e)=>setForm({...form,rightName:e.target.value})} placeholder="Cristiano Ronaldo" className="input"/></Field><label className="flex items-center gap-3 rounded-2xl border border-white/10 bg-[#07111f] px-4"><input type="checkbox" checked={form.isActive} onChange={(e)=>setForm({...form,isActive:e.target.checked})}/><span className="font-black">Aktif</span></label></div>
   <button onClick={()=>void save()} disabled={saving} className="mt-5 min-h-12 rounded-xl bg-green-500 px-6 font-black text-[#07111f] disabled:opacity-50">{saving?"Kaydediliyor...":editing?"Değişiklikleri Kaydet":"Kapışmayı Oluştur"}</button>{message&&<p className="mt-3 text-sm font-bold text-yellow-200">{message}</p>}
  </section>
  <section className="mt-7"><h2 className="text-2xl font-black">Planlanan Kapışmalar</h2>{loading?<p className="mt-4 text-slate-500">Yükleniyor...</p>:<div className="mt-4 grid gap-4">{items.map(item=><article key={item.id} className="rounded-3xl border border-white/10 bg-[#0d1828] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs text-slate-500">{item.matchDate}</p><h3 className="mt-2 text-xl font-black">{item.leftName} <span className="text-orange-300">VS</span> {item.rightName}</h3><p className="mt-2 text-sm">🇹🇷 {item.titleTr} · {item.categoryTr}</p><p className="mt-1 text-sm text-green-300">🇬🇧 {item.titleEn||item.titleTr} · {item.categoryEn||item.categoryTr}</p><p className="mt-2 text-xs text-slate-500">🗳️ {item.votes.total} oy</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>edit(item)} className="btn">Düzenle</button><button onClick={()=>void toggle(item)} className="btn">{item.isActive?"Pasife Al":"Aktifleştir"}</button><button onClick={()=>void remove(item)} className="btn">Sil</button></div></div></article>)}</div>}</section>
 </div><style jsx global>{`.input{width:100%;min-height:48px;border-radius:12px;border:1px solid rgba(255,255,255,.1);background:#07111f;padding:0 14px;color:white;outline:none}.btn{border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:8px 14px;font-size:14px;font-weight:800}`}</style></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">{label}</span>{children}</label>}
function Stat({value,label}:{value:string;label:string}){return <div className="min-w-[110px] rounded-2xl border border-white/10 bg-white/[.035] px-4 py-3"><p className="text-2xl font-black text-green-300">{value}</p><p className="text-[10px] font-black uppercase text-slate-600">{label}</p></div>}
