"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { Locale } from "@/lib/i18n/config";

type RankedEntry = { position:number|null; userId:string; username?:string|null; displayName?:string; rankName?:string; rankIcon?:string; lp:number; wins:number; losses:number; gamesPlayed:number };
type RankedData = { ok?:boolean; season?:{title?:string}|null; leaderboard?:RankedEntry[]; me?:RankedEntry|null };
type SoloEntry = { position:number|null; userId:string; username?:string|null; displayName?:string; rating:number; gamesPlayed:number; gamesCount:number; wins:number };
type SoloData = { ok?:boolean; leaderboard?:SoloEntry[]; me?:SoloEntry|null };
type Friend = { user:{ id:string; username:string|null; displayName:string } };
type FriendsData = { ok?:boolean; friends?:Friend[] };

export default function MobileLeaderboardPage({ locale }: { locale: Locale }) {
  const tr = locale === "tr";
  const [mode,setMode]=useState<"ranked"|"solo">("solo");
  const [scope,setScope]=useState<"global"|"friends">("global");
  const [ranked,setRanked]=useState<RankedData|null>(null); const [solo,setSolo]=useState<SoloData|null>(null); const [friends,setFriends]=useState<FriendsData|null>(null); const [loading,setLoading]=useState(true);
  const nf=useMemo(()=>new Intl.NumberFormat(tr?"tr-TR":"en-US"),[tr]);
  useEffect(()=>{void Promise.all([fetch("/api/rank/leaderboard",{cache:"no-store"}).then(r=>r.json()),fetch("/api/solo/leaderboard",{cache:"no-store"}).then(r=>r.json()),fetch("/api/friends",{cache:"no-store"}).then(async r=>r.ok?r.json():({ok:false}))]).then(([a,b,c])=>{setRanked(a);setSolo(b);setFriends(c)}).finally(()=>setLoading(false))},[]);
  const friendIds=useMemo(()=>new Set((friends?.friends??[]).map(i=>i.user.id)),[friends]);
  const rankedEntries=useMemo(()=>{const rows=[...(ranked?.leaderboard??[])];if(scope==="global")return rows;const allowed=new Set(friendIds);if(ranked?.me?.userId)allowed.add(ranked.me.userId);const f=rows.filter(e=>allowed.has(e.userId));if(ranked?.me&&!f.some(e=>e.userId===ranked.me?.userId))f.push(ranked.me);f.sort((a,b)=>Number(b.lp??0)-Number(a.lp??0));return f},[ranked,scope,friendIds]);
  const soloEntries=useMemo(()=>{const rows=[...(solo?.leaderboard??[])];if(scope==="global")return rows;const allowed=new Set(friendIds);if(solo?.me?.userId)allowed.add(solo.me.userId);const f=rows.filter(e=>allowed.has(e.userId));if(solo?.me&&!f.some(e=>e.userId===solo.me?.userId))f.push(solo.me);f.sort((a,b)=>Number(b.rating??0)-Number(a.rating??0));return f},[solo,scope,friendIds]);
  const medal=(position:number|null)=>position===1?"🥇":position===2?"🥈":position===3?"🥉":"🏅";
  return <main className="min-h-screen bg-[#07111f] px-4 pb-24 pt-5 text-white"><div className="mx-auto max-w-xl">
    <header><Link href={`/${locale}`} className="inline-flex" aria-label="FootBattle"><img src="/footbattle-logo.png" alt="FootBattle" className="h-9 w-auto object-contain"/></Link><p className="mt-6 text-[10px] font-black uppercase tracking-[0.2em] text-yellow-300">{tr?"Sıralama":"Leaderboard"}</p><h1 className="mt-1 text-3xl font-black">{tr?"FootBattle Sıralaması":"FootBattle Leaderboard"}</h1><p className="mt-1 text-xs text-slate-500">{tr?"Sıralama puanı ve Ranked ELO ayrı tutulur.":"Leaderboard score and Ranked ELO are tracked separately."}</p></header>
    <div className="mt-6 grid grid-cols-2 rounded-2xl border border-white/10 bg-white/[0.025] p-1"><button onClick={()=>setMode("solo")} className={`rounded-xl px-3 py-3 text-sm font-black ${mode==="solo"?"bg-green-500 text-[#07111f]":"text-slate-500"}`}>🏅 {tr?"Sıralama":"Leaderboard"}</button><button onClick={()=>setMode("ranked")} className={`rounded-xl px-3 py-3 text-sm font-black ${mode==="ranked"?"bg-green-500 text-[#07111f]":"text-slate-500"}`}>🏆 Ranked</button></div>
    <div className="mt-5 flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-slate-500">{mode==="ranked"?"Ranked ELO":(tr?"Sıralama":"Leaderboard")}</p><h2 className="mt-1 text-xl font-black">{mode==="ranked"?(ranked?.season?.title??(tr?"Ranked sıralaması":"Ranked leaderboard")):(tr?"Genel sıralama":"Overall leaderboard")}</h2></div><p className="max-w-[180px] text-right text-[10px] leading-4 text-slate-600">{mode==="ranked"?(tr?"Yalnızca gerçek oyuncular arasındaki Ranked maçlar.":"Only Ranked matches between real players."):(tr?"Solo oyunlardan kazanılan toplam puana göre sıralama.":"Ranking by total score earned from solo games.")}</p></div>
    <div className="mt-4 grid grid-cols-2 rounded-2xl border border-white/10 bg-white/[0.025] p-1"><button onClick={()=>setScope("global")} className={`rounded-xl px-3 py-2.5 text-xs font-black ${scope==="global"?"bg-slate-700 text-white":"text-slate-500"}`}>{tr?"🌍 Genel":"🌍 Global"}</button><button onClick={()=>setScope("friends")} className={`rounded-xl px-3 py-2.5 text-xs font-black ${scope==="friends"?"bg-slate-700 text-white":"text-slate-500"}`}>{tr?"👥 Arkadaşlar":"👥 Friends"}</button></div>
    <section className="mt-4 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">{loading?<p className="p-8 text-center text-sm text-slate-500">{tr?"Yükleniyor...":"Loading..."}</p>:mode==="ranked"?(rankedEntries.length===0?<p className="p-8 text-center text-sm text-slate-500">{tr?"Sıralama boş.":"Leaderboard is empty."}</p>:<div className="divide-y divide-white/[0.06]">{rankedEntries.map((e,i)=>{const pos=scope==="global"?e.position:i+1;const row=<><span className="w-8 shrink-0 text-center text-xs font-black">#{pos??"-"}</span>{e.rankIcon?<img src={e.rankIcon} alt={e.rankName??"Rank"} className="h-11 w-11 shrink-0 object-contain"/>:<span className="flex h-11 w-11 items-center justify-center text-xl">🏆</span>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{e.displayName??e.username??"FootBattle"}</p><p className="mt-0.5 truncate text-[9px] text-slate-600">{e.rankName??"Ranked"} · {e.gamesPlayed} {tr?"maç":"matches"} · {e.wins}G/{e.losses}M</p></div><div className="shrink-0 text-right"><p className="text-sm font-black text-green-300">{nf.format(e.lp)}</p><p className="text-[8px] font-black text-slate-600">ELO</p></div></>;return e.username?<Link key={e.userId} href={`/u/${encodeURIComponent(e.username)}`} className="flex items-center gap-2.5 px-3 py-3">{row}</Link>:<div key={e.userId} className="flex items-center gap-2.5 px-3 py-3">{row}</div>})}</div>):(soloEntries.length===0?<p className="p-8 text-center text-sm text-slate-500">{tr?"Henüz puanlı oyun yok.":"No scored games yet."}</p>:<div className="divide-y divide-white/[0.06]">{soloEntries.map((e,i)=>{const pos=scope==="global"?e.position:i+1;const row=<><span className="w-8 shrink-0 text-center text-xs font-black">#{pos??"-"}</span><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-yellow-500/10 text-xl">{medal(pos)}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{e.displayName??e.username??"FootBattle"}</p><p className="mt-0.5 truncate text-[9px] text-slate-600">{e.gamesCount} {tr?"oyun türü":"game types"} · {e.gamesPlayed} {tr?"oyun":"games"} · {e.wins} {tr?"galibiyet":"wins"}</p></div><div className="shrink-0 text-right"><p className="text-sm font-black text-yellow-300">{nf.format(e.rating)}</p><p className="text-[8px] font-black text-slate-600">{tr?"PUAN":"SCORE"}</p></div></>;return e.username?<Link key={e.userId} href={`/u/${encodeURIComponent(e.username)}`} className="flex items-center gap-2.5 px-3 py-3">{row}</Link>:<div key={e.userId} className="flex items-center gap-2.5 px-3 py-3">{row}</div>})}</div>)}</section>
  </div></main>;
}
