-- FootBattle competitive LP / rank system.
-- XP remains permanent progression. LP is seasonal competitive progression.

alter table if exists public.game_sessions
  add column if not exists rank_processed boolean not null default false;

create table if not exists public.rank_seasons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz null,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists rank_seasons_single_active_idx
  on public.rank_seasons(is_active) where is_active = true;

create table if not exists public.user_rank_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  season_id uuid not null references public.rank_seasons(id) on delete cascade,
  lp integer not null default 0 check (lp >= 0),
  peak_lp integer not null default 0 check (peak_lp >= 0),
  rank_code text not null default 'bronze_3',
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  games_played integer not null default 0 check (games_played >= 0),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  primary key (user_id, season_id)
);

create table if not exists public.rank_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  season_id uuid not null references public.rank_seasons(id) on delete cascade,
  game_session_id uuid not null unique references public.game_sessions(id) on delete cascade,
  game_code text not null,
  lp_before integer not null,
  lp_change integer not null,
  lp_after integer not null,
  rank_before text not null,
  rank_after text not null,
  created_at timestamptz not null default now()
);

create index if not exists user_rank_progress_board_idx
  on public.user_rank_progress(season_id, lp desc, wins desc, games_played asc);
create index if not exists rank_history_user_idx
  on public.rank_history(user_id, created_at desc);
create index if not exists game_sessions_rank_idx
  on public.game_sessions(rank_processed, status, score_blocked, finished_at desc);

alter table public.rank_seasons enable row level security;
alter table public.user_rank_progress enable row level security;
alter table public.rank_history enable row level security;

drop policy if exists "active rank seasons readable" on public.rank_seasons;
create policy "active rank seasons readable" on public.rank_seasons
  for select to authenticated, anon using (is_active = true);

drop policy if exists "rank progress readable" on public.user_rank_progress;
create policy "rank progress readable" on public.user_rank_progress
  for select to authenticated, anon using (true);

drop policy if exists "rank history readable by owner" on public.rank_history;
create policy "rank history readable by owner" on public.rank_history
  for select to authenticated using (auth.uid() = user_id);

insert into public.rank_seasons(code, title, starts_at, is_active)
values ('2026-s1', '2026 Sezon 1', now(), true)
on conflict (code) do update set title = excluded.title;

create or replace function public.footbattle_rank_for_lp(p_lp integer)
returns text language sql immutable as $$
  select case
    when greatest(coalesce(p_lp, 0), 0) >= 12500 then 'goat'
    when p_lp >= 10000 then 'legend_1'
    when p_lp >= 8500 then 'legend_2'
    when p_lp >= 7000 then 'legend_3'
    when p_lp >= 5500 then 'diamond_1'
    when p_lp >= 4500 then 'diamond_2'
    when p_lp >= 3700 then 'diamond_3'
    when p_lp >= 3000 then 'platinum_1'
    when p_lp >= 2500 then 'platinum_2'
    when p_lp >= 2000 then 'platinum_3'
    when p_lp >= 1600 then 'gold_1'
    when p_lp >= 1300 then 'gold_2'
    when p_lp >= 1000 then 'gold_3'
    when p_lp >= 700 then 'silver_1'
    when p_lp >= 500 then 'silver_2'
    when p_lp >= 350 then 'silver_3'
    when p_lp >= 200 then 'bronze_1'
    when p_lp >= 100 then 'bronze_2'
    else 'bronze_3'
  end
$$;

create or replace function public.footbattle_lp_for_result(
  p_game_code text,
  p_score integer,
  p_won boolean
)
returns integer language sql immutable as $$
  select case
    when coalesce(p_won, false) then
      15 + least(25, greatest(0, coalesce(p_score, 0)) / 20)
      + case when p_game_code in ('tic_tac_toe', 'club_clash', 'club_nation') then 10 else 0 end
    else
      case when p_game_code in ('tic_tac_toe', 'club_clash', 'club_nation') then -12 else -5 end
  end
$$;

create or replace function public.footbattle_apply_rank()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_claimed uuid;
  v_season uuid;
  v_existing public.user_rank_progress%rowtype;
  v_change integer;
  v_before integer;
  v_after integer;
  v_rank_before text;
  v_rank_after text;
begin
  if new.user_id is null
     or new.status <> 'finished'
     or new.score_blocked = true
     or new.rank_processed = true then
    return new;
  end if;

  select id into v_season
    from public.rank_seasons
   where is_active = true
   order by starts_at desc
   limit 1;

  if v_season is null then return new; end if;

  update public.game_sessions
     set rank_processed = true,
         updated_at = now()
   where id = new.id
     and rank_processed = false
  returning id into v_claimed;

  if v_claimed is null then return new; end if;

  insert into public.user_rank_progress(user_id, season_id)
  values (new.user_id, v_season)
  on conflict (user_id, season_id) do nothing;

  select * into v_existing
    from public.user_rank_progress
   where user_id = new.user_id and season_id = v_season
   for update;

  v_before := v_existing.lp;
  v_rank_before := public.footbattle_rank_for_lp(v_before);
  v_change := public.footbattle_lp_for_result(new.game_code, coalesce(new.server_score, 0), new.won);
  v_after := greatest(0, v_before + v_change);
  v_rank_after := public.footbattle_rank_for_lp(v_after);

  update public.user_rank_progress
     set lp = v_after,
         peak_lp = greatest(peak_lp, v_after),
         rank_code = v_rank_after,
         wins = wins + case when coalesce(new.won, false) then 1 else 0 end,
         losses = losses + case when coalesce(new.won, false) then 0 else 1 end,
         games_played = games_played + 1,
         updated_at = now()
   where user_id = new.user_id and season_id = v_season;

  insert into public.rank_history(
    user_id, season_id, game_session_id, game_code,
    lp_before, lp_change, lp_after, rank_before, rank_after
  ) values (
    new.user_id, v_season, new.id, new.game_code,
    v_before, v_change, v_after, v_rank_before, v_rank_after
  ) on conflict (game_session_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_footbattle_rank on public.game_sessions;
create trigger trg_footbattle_rank
after insert or update on public.game_sessions
for each row execute function public.footbattle_apply_rank();

-- Existing approved sessions are intentionally not backfilled into LP.
-- Rank competition starts from the moment this migration is applied.
update public.game_sessions
   set rank_processed = true
 where status = 'finished'
   and user_id is not null
   and score_blocked = false;

insert into public.user_rank_progress(user_id, season_id)
select p.id, s.id
  from public.profiles p
 cross join public.rank_seasons s
 where s.is_active = true
on conflict (user_id, season_id) do nothing;
