-- FootBattle Tic Tac Toe duel storage.
-- Shared grid, side-specific attempts. Server-side only.

create table if not exists public.tic_tac_toe_duels (
  id uuid primary key default gen_random_uuid(),
  challenge_id bigint not null unique,
  rows jsonb not null,
  columns jsonb not null,
  grid_cells jsonb not null,
  duration_seconds integer not null default 120 check (duration_seconds between 30 and 600),
  started_at timestamptz not null default now(),
  challenger_finished_at timestamptz null,
  opponent_finished_at timestamptz null,
  finalized_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tic_tac_toe_duel_attempts (
  id bigint generated by default as identity primary key,
  duel_id uuid not null references public.tic_tac_toe_duels(id) on delete cascade,
  side text not null check (side in ('challenger', 'opponent')),
  row_index integer not null check (row_index between 0 and 2),
  column_index integer not null check (column_index between 0 and 2),
  player_id integer not null,
  correct boolean not null default false,
  answered_at timestamptz not null default now()
);

create index if not exists tic_tac_toe_duels_challenge_idx
  on public.tic_tac_toe_duels(challenge_id);

create index if not exists tic_tac_toe_duel_attempts_duel_side_idx
  on public.tic_tac_toe_duel_attempts(duel_id, side, answered_at desc);

create unique index if not exists tic_tac_toe_duel_correct_cell_unique
  on public.tic_tac_toe_duel_attempts(duel_id, side, row_index, column_index)
  where correct = true;

create unique index if not exists tic_tac_toe_duel_correct_player_unique
  on public.tic_tac_toe_duel_attempts(duel_id, side, player_id)
  where correct = true;

alter table public.tic_tac_toe_duels enable row level security;
alter table public.tic_tac_toe_duel_attempts enable row level security;

-- No anon/authenticated policies: all reads/writes go through server-side API routes.