-- FootBattle referral / invite system

create table if not exists public.referral_codes (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  code text not null unique check (char_length(code) between 6 and 16),
  click_count integer not null default 0 check (click_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.referral_conversions (
  id bigint generated by default as identity primary key,
  inviter_id uuid not null references public.profiles(id) on delete cascade,
  invitee_id uuid not null unique references public.profiles(id) on delete cascade,
  referral_code text not null,
  inviter_xp integer not null default 250,
  invitee_xp integer not null default 100,
  created_at timestamptz not null default now(),
  check (inviter_id <> invitee_id)
);

create index if not exists referral_conversions_inviter_idx
  on public.referral_conversions(inviter_id, created_at desc);

alter table public.referral_codes enable row level security;
alter table public.referral_conversions enable row level security;

-- App accesses referral data through authenticated server-side API routes.

create or replace function public.footbattle_claim_referral(p_code text, p_invitee uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inviter uuid;
  v_existing bigint;
  v_inviter_xp constant integer := 250;
  v_invitee_xp constant integer := 100;
  v_next_xp bigint;
begin
  select user_id into v_inviter
    from public.referral_codes
   where upper(code) = upper(trim(p_code));

  if v_inviter is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_code');
  end if;

  if v_inviter = p_invitee then
    return jsonb_build_object('ok', false, 'reason', 'self_referral');
  end if;

  select id into v_existing
    from public.referral_conversions
   where invitee_id = p_invitee;

  if v_existing is not null then
    return jsonb_build_object('ok', true, 'already_claimed', true);
  end if;

  insert into public.referral_conversions(inviter_id, invitee_id, referral_code, inviter_xp, invitee_xp)
  values (v_inviter, p_invitee, upper(trim(p_code)), v_inviter_xp, v_invitee_xp);

  insert into public.user_progress(user_id) values (v_inviter)
  on conflict (user_id) do nothing;
  insert into public.user_progress(user_id) values (p_invitee)
  on conflict (user_id) do nothing;

  update public.user_progress
     set xp = xp + v_inviter_xp,
         level = public.footbattle_level_for_xp(xp + v_inviter_xp),
         updated_at = now()
   where user_id = v_inviter
  returning xp into v_next_xp;

  update public.user_progress
     set xp = xp + v_invitee_xp,
         level = public.footbattle_level_for_xp(xp + v_invitee_xp),
         updated_at = now()
   where user_id = p_invitee;

  perform public.footbattle_award_achievements(v_inviter);
  perform public.footbattle_award_achievements(p_invitee);

  return jsonb_build_object(
    'ok', true,
    'already_claimed', false,
    'inviter_id', v_inviter,
    'inviter_xp', v_inviter_xp,
    'invitee_xp', v_invitee_xp
  );
exception
  when unique_violation then
    return jsonb_build_object('ok', true, 'already_claimed', true);
end;
$$;
