-- FootBattle universal game session / anti-cheat ledger.
-- Existing game-specific session tables remain the gameplay source of truth.
-- These tables add a common server-side audit layer across every score-producing game.

create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  game_code text not null,
  source_session_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  mode text not null default 'solo',
  status text not null default 'active' check (status in ('active', 'finished', 'abandoned', 'rejected')),
  started_at timestamptz not null default now(),
  expires_at timestamptz null,
  finished_at timestamptz null,
  server_score integer null,
  won boolean null,
  duration_ms bigint null,
  suspicion_score integer not null default 0 check (suspicion_score >= 0),
  suspicious boolean not null default false,
  score_blocked boolean not null default false,
  client_fingerprint text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_code, source_session_id)
);

create index if not exists game_sessions_user_id_idx
  on public.game_sessions(user_id, started_at desc);

create index if not exists game_sessions_game_code_idx
  on public.game_sessions(game_code, started_at desc);

create index if not exists game_sessions_suspicious_idx
  on public.game_sessions(suspicious, score_blocked, started_at desc);

create table if not exists public.game_session_events (
  id bigint generated by default as identity primary key,
  game_session_id uuid not null references public.game_sessions(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists game_session_events_session_idx
  on public.game_session_events(game_session_id, id);

create index if not exists game_session_events_type_idx
  on public.game_session_events(event_type, created_at desc);

create table if not exists public.game_security_events (
  id bigint generated by default as identity primary key,
  game_session_id uuid not null references public.game_sessions(id) on delete cascade,
  game_code text not null,
  source_session_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  reason text not null,
  points integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists game_security_events_session_idx
  on public.game_security_events(game_session_id, created_at desc);

create index if not exists game_security_events_user_idx
  on public.game_security_events(user_id, created_at desc);

alter table public.game_sessions enable row level security;
alter table public.game_session_events enable row level security;
alter table public.game_security_events enable row level security;

-- No anon/authenticated policies on purpose. These tables are accessed only
-- by server-side routes through the Supabase secret/service-role client.
