-- FootBattle Günün Kapışması

create table if not exists public.daily_faceoffs (
  id uuid primary key default gen_random_uuid(),
  match_date date not null unique,
  title text not null default 'Günün Kapışması' check (char_length(title) between 1 and 80),
  category text not null default 'Genel' check (char_length(category) between 1 and 60),
  left_name text not null check (char_length(left_name) between 1 and 80),
  right_name text not null check (char_length(right_name) between 1 and 80),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_faceoff_votes (
  id bigint generated by default as identity primary key,
  faceoff_id uuid not null references public.daily_faceoffs(id) on delete cascade,
  voter_key text not null check (char_length(voter_key) between 3 and 120),
  user_id uuid null references auth.users(id) on delete set null,
  choice text not null check (choice in ('left', 'right')),
  created_at timestamptz not null default now(),
  unique (faceoff_id, voter_key)
);

create index if not exists daily_faceoffs_date_idx
  on public.daily_faceoffs(match_date desc, is_active);
create index if not exists daily_faceoff_votes_faceoff_idx
  on public.daily_faceoff_votes(faceoff_id, choice);
create index if not exists daily_faceoff_votes_user_idx
  on public.daily_faceoff_votes(user_id, created_at desc)
  where user_id is not null;

alter table public.daily_faceoffs enable row level security;
alter table public.daily_faceoff_votes enable row level security;

-- API routes access these tables server-side with the Supabase secret key.

insert into public.daily_faceoffs(match_date, category, left_name, right_name)
values
  ('2026-08-15', 'GOAT', 'Lionel Messi', 'Cristiano Ronaldo'),
  ('2026-08-16', 'Süper Lig Efsaneleri', 'Gheorghe Hagi', 'Alex de Souza'),
  ('2026-08-17', 'Orta Saha', 'Xavi Hernández', 'Andrés Iniesta'),
  ('2026-08-18', 'Premier League', 'Thierry Henry', 'Didier Drogba'),
  ('2026-08-19', 'Orta Saha', 'Luka Modrić', 'Toni Kroos'),
  ('2026-08-20', 'Brezilya', 'Neymar', 'Ronaldinho'),
  ('2026-08-21', 'Kaleciler', 'Gianluigi Buffon', 'Iker Casillas')
on conflict (match_date) do nothing;
