-- Ranked-only Elo model for FootBattle.
-- Solo game sessions no longer affect competitive ranking.

alter table if exists public.user_rank_progress
  add column if not exists elo integer not null default 1000,
  add column if not exists peak_elo integer not null default 1000;

alter table if exists public.ranked_matches
  add column if not exists rating_processed boolean not null default false;

create table if not exists public.ranked_elo_history (
  id bigint generated by default as identity primary key,
  ranked_match_id uuid not null references public.ranked_matches(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  season_id uuid not null references public.rank_seasons(id) on delete cascade,
  elo_before integer not null,
  elo_change integer not null,
  elo_after integer not null,
  created_at timestamptz not null default now(),
  unique (ranked_match_id, user_id)
);

alter table public.ranked_elo_history enable row level security;
drop policy if exists "ranked elo history readable by owner" on public.ranked_elo_history;
create policy "ranked elo history readable by owner" on public.ranked_elo_history
  for select to authenticated using (auth.uid() = user_id);

-- Old trigger ranked solo game_sessions. Competitive rank is now Ranked-only.
drop trigger if exists trg_footbattle_rank on public.game_sessions;

create or replace function public.footbattle_rank_for_elo(p_elo integer)
returns text language sql immutable as $$
  select case
    when greatest(coalesce(p_elo, 1000), 0) >= 2800 then 'goat'
    when p_elo >= 2700 then 'legend_1'
    when p_elo >= 2600 then 'legend_2'
    when p_elo >= 2500 then 'legend_3'
    when p_elo >= 2400 then 'diamond_1'
    when p_elo >= 2300 then 'diamond_2'
    when p_elo >= 2200 then 'diamond_3'
    when p_elo >= 2100 then 'platinum_1'
    when p_elo >= 2000 then 'platinum_2'
    when p_elo >= 1900 then 'platinum_3'
    when p_elo >= 1800 then 'gold_1'
    when p_elo >= 1700 then 'gold_2'
    when p_elo >= 1600 then 'gold_3'
    when p_elo >= 1500 then 'silver_1'
    when p_elo >= 1400 then 'silver_2'
    when p_elo >= 1300 then 'silver_3'
    when p_elo >= 1200 then 'bronze_1'
    when p_elo >= 1100 then 'bronze_2'
    else 'bronze_3'
  end
$$;

create or replace function public.footbattle_apply_ranked_elo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season uuid;
  v_a public.user_rank_progress%rowtype;
  v_b public.user_rank_progress%rowtype;
  v_expected_a double precision;
  v_expected_b double precision;
  v_score_a double precision;
  v_score_b double precision;
  v_change_a integer;
  v_change_b integer;
  v_after_a integer;
  v_after_b integer;
  v_now timestamptz := now();
begin
  -- Only completed human-vs-human Ranked matches affect Elo.
  if new.status <> 'completed'
     or new.rating_processed = true
     or new.opponent_kind <> 'human'
     or new.player_a_id is null
     or new.player_b_id is null then
    return new;
  end if;

  select id into v_season
    from public.rank_seasons
   where is_active = true
   order by starts_at desc
   limit 1;
  if v_season is null then return new; end if;

  -- Claim exactly once. The recursive trigger call sees rating_processed=true.
  update public.ranked_matches
     set rating_processed = true,
         updated_at = v_now
   where id = new.id
     and rating_processed = false;
  if not found then return new; end if;

  insert into public.user_rank_progress(user_id, season_id, elo, peak_elo)
  values (new.player_a_id, v_season, 1000, 1000)
  on conflict (user_id, season_id) do nothing;

  insert into public.user_rank_progress(user_id, season_id, elo, peak_elo)
  values (new.player_b_id, v_season, 1000, 1000)
  on conflict (user_id, season_id) do nothing;

  -- Lock in deterministic user-id order to reduce deadlock risk.
  perform 1 from public.user_rank_progress
   where season_id = v_season and user_id in (new.player_a_id, new.player_b_id)
   order by user_id for update;

  select * into v_a from public.user_rank_progress where user_id = new.player_a_id and season_id = v_season;
  select * into v_b from public.user_rank_progress where user_id = new.player_b_id and season_id = v_season;

  v_expected_a := 1.0 / (1.0 + power(10.0, (v_b.elo - v_a.elo)::double precision / 400.0));
  v_expected_b := 1.0 - v_expected_a;

  if new.winner_user_id = new.player_a_id then
    v_score_a := 1.0; v_score_b := 0.0;
  elsif new.winner_user_id = new.player_b_id then
    v_score_a := 0.0; v_score_b := 1.0;
  else
    v_score_a := 0.5; v_score_b := 0.5;
  end if;

  -- K=40 during early competitive lifecycle.
  v_change_a := round(40.0 * (v_score_a - v_expected_a));
  v_change_b := round(40.0 * (v_score_b - v_expected_b));
  v_after_a := greatest(100, v_a.elo + v_change_a);
  v_after_b := greatest(100, v_b.elo + v_change_b);

  update public.user_rank_progress
     set elo = v_after_a,
         peak_elo = greatest(peak_elo, v_after_a),
         rank_code = public.footbattle_rank_for_elo(v_after_a),
         wins = wins + case when v_score_a = 1.0 then 1 else 0 end,
         losses = losses + case when v_score_a = 0.0 then 1 else 0 end,
         games_played = games_played + 1,
         updated_at = v_now
   where user_id = new.player_a_id and season_id = v_season;

  update public.user_rank_progress
     set elo = v_after_b,
         peak_elo = greatest(peak_elo, v_after_b),
         rank_code = public.footbattle_rank_for_elo(v_after_b),
         wins = wins + case when v_score_b = 1.0 then 1 else 0 end,
         losses = losses + case when v_score_b = 0.0 then 1 else 0 end,
         games_played = games_played + 1,
         updated_at = v_now
   where user_id = new.player_b_id and season_id = v_season;

  insert into public.ranked_elo_history(ranked_match_id,user_id,season_id,elo_before,elo_change,elo_after)
  values
    (new.id,new.player_a_id,v_season,v_a.elo,v_change_a,v_after_a),
    (new.id,new.player_b_id,v_season,v_b.elo,v_change_b,v_after_b)
  on conflict (ranked_match_id,user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_footbattle_ranked_elo on public.ranked_matches;
create trigger trg_footbattle_ranked_elo
after insert or update of status, winner_user_id on public.ranked_matches
for each row execute function public.footbattle_apply_ranked_elo();

-- Current season was test data and included solo LP. Start the Ranked-only ladder cleanly.
update public.user_rank_progress p
   set elo = 1000,
       peak_elo = 1000,
       lp = 0,
       peak_lp = 0,
       rank_code = 'bronze_3',
       wins = 0,
       losses = 0,
       games_played = 0,
       updated_at = now()
 where exists (select 1 from public.rank_seasons s where s.id = p.season_id and s.is_active = true);

update public.ranked_matches
   set rating_processed = true
 where status = 'completed';
