-- FootBattle Tic Tac Toe duel storage.
-- Shared grid, side-specific attempts. Server-side only.

-- Older environments may have a CHECK constraint that lists the allowed
-- guest_challenges game codes. Replace only game_code CHECK constraints so
-- Tic Tac Toe can use the existing challenge/join/start infrastructure.
do $$
declare
  constraint_row record;
begin
  if to_regclass('public.guest_challenges') is not null then
    for constraint_row in
      select c.conname
        from pg_constraint c
        join pg_class t on t.oid = c.conrelid
        join pg_namespace n on n.oid = t.relnamespace
       where n.nspname = 'public'
         and t.relname = 'guest_challenges'
         and c.contype = 'c'
         and pg_get_constraintdef(c.oid) ilike '%game_code%'
    loop
      execute format(
        'alter table public.guest_challenges drop constraint %I',
        constraint_row.conname
      );
    end loop;

    alter table public.guest_challenges
      add constraint guest_challenges_game_code_check
      check (
        game_code in (
          'club_clash',
          'club_nation',
          'player_quiz',
          'career_path',
          'guess_the_player',
          'tic_tac_toe'
        )
      );
  end if;
end
$$;

create table if not exists public.tic_tac_toe_duels (
  id uuid primary key default gen_random_uuid(),
  challenge_id bigint not null unique,
  rows jsonb not null,
  columns jsonb not null,
  grid_cells jsonb not null,
  duration_seconds integer not null default 120 check (duration_seconds between 30 and 600),
  started_at timestamptz not null default now(),
  challenger_finished_at timestamptz null,
  opponent_finished_at timestamptz null,
  finalized_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tic_tac_toe_duel_attempts (
  id bigint generated by default as identity primary key,
  duel_id uuid not null references public.tic_tac_toe_duels(id) on delete cascade,
  side text not null check (side in ('challenger', 'opponent')),
  row_index integer not null check (row_index between 0 and 2),
  column_index integer not null check (column_index between 0 and 2),
  player_id integer not null,
  correct boolean not null default false,
  answered_at timestamptz not null default now()
);

create index if not exists tic_tac_toe_duels_challenge_idx
  on public.tic_tac_toe_duels(challenge_id);

create index if not exists tic_tac_toe_duel_attempts_duel_side_idx
  on public.tic_tac_toe_duel_attempts(duel_id, side, answered_at desc);

create unique index if not exists tic_tac_toe_duel_correct_cell_unique
  on public.tic_tac_toe_duel_attempts(duel_id, side, row_index, column_index)
  where correct = true;

create unique index if not exists tic_tac_toe_duel_correct_player_unique
  on public.tic_tac_toe_duel_attempts(duel_id, side, player_id)
  where correct = true;

alter table public.tic_tac_toe_duels enable row level security;
alter table public.tic_tac_toe_duel_attempts enable row level security;

-- No anon/authenticated policies: all reads/writes go through server-side API routes.